In [1]:
import numpy as np

In [ ]:
#Array de uma deimensão

array_1d = np.array([1,2,3,4,5])
print(array_1d.ndim)
print(array_1d.shape)
print(array_1d)
#muito usados com series temporais

1
(5,)
[1 2 3 4 5]


In [7]:
#Array de duas dimanesões

array_2d = np.array([[1,2,3], [4,5,6]])
print(array_2d.ndim)
print(array_2d.shape)
print(array_2d)

#muito usado em matrizes, imagens e tabelas de dados

2
(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
#Array de Trêsa dimensões

array_3d = np.array([[[1,2,3], [4,5,6], [7,8,9], [10,11,12]]])
print(array_3d.ndim)
print(array_3d.shape)
array_3d
#é usado em imagens em cores com cada matriz respensentado uma canal de cor

3
(1, 4, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
#Array de Trêsa dimensões

array_4d = np.array([[[[1,2,3], [4,5,6], [7,8,9], [10,11,12]]]])
print(array_4d.ndim)
print(array_4d.shape)
array_4d
#é usado em imagens em cores com cada matriz respensentado uma canal de cor

4
(1, 1, 4, 3)


array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])