In [11]:
import numpy as np1

In [16]:
#Matriz fromada por um array de duas dimanesões.

array = np1.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
print(array.ndim)
print(array.shape)
array

2
(4, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [17]:
#Fatiamento das duas primeiras linhas
#Quando você usa somente isso (:) eke subentende que você quer pegar o array (linha ou coluna) todo.

fatiamentoTreslinhas = array[0:2,:]
fatiamentoTreslinhas

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
#Fatiando as três primeiras colunas
#O ultimo sempre e exclusivo na indexasão, logo sempre sera de 0 a n-1

fatiamentoTresColunas  = array[:, 0:3]
fatiamentoTresColunas

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [21]:
#SubArray central

subArrayCentral = array[1:3, 1:4]
subArrayCentral

array([[ 7,  8,  9],
       [12, 13, 14]])

In [ ]:
#S ubArray Lateral

subArrayLateral = array[2:4, 3:5]
subArrayLateral

array([[11, 11],
       [22, 22]])

In [31]:
#Modificando um sub Array de nDimensões
#Sempre print para ter uma boa visuaização do problema

array[1:3, 1:3] = [[99,100], [101,102]]
array

array([[  1,   2,   3,   4,   5],
       [  6,  99, 100,   9,  10],
       [ 11, 101, 102,  11,  11],
       [ 16,  17,  18,  22,  22]])