In [2]:
import numpy as np

In [7]:
array = np.array([[10,20,30], [40,50,60], [70,80,90]])
print(array.ndim)
print(array.shape)
array

2
(3, 3)


array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
#Acessar uma posição especifica do array
#A indexação começa com 0 no Python
elemento = array[1, 2]
elemento



np.int64(60)

In [13]:
#Pegar dados da primeira linha e primeira coluna

linha0 = array[0,]
linha0

coluna0 = array[:,0]
coluna0

array([10, 40, 70])

In [15]:
#Fatiamento para conseguir um SubArray

subArray = array[0:2, 1:3]
print(array)
subArray

[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([[20, 30],
       [50, 60]])

In [ ]:
#Uma é a ultilização de  algum operador, no caso abaixo o de comparação
#Para atrivuir a matriz que é um array de duas dimensões uma seríe de Trues
#e Falses, que posem ser usados como filtro para operaçõe de tratamento de dados!
mascara =  array > 50
mascara


array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [18]:
elementos_maiores_que_50 = array[mascara]
elementos_maiores_que_50

array([60, 70, 80, 90])

In [20]:
array[1, 1] = 100
array

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])